version: '{build}'
skip_tags: true
image: Visual Studio 2015
configuration: Release
clone_depth: 1
before_build:
- ps: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Installer\bin\Release\polutils.msi
  name: polutils.msi
before_deploy:
- ps: >-
    $env:BUILD_VERSION_STRING = [System.Diagnostics.FileVersionInfo]::GetVersionInfo((Join-Path $env:APPVEYOR_BUILD_FOLDER 'POLUtils\bin\Release\POLUtils.exe')).FileVersion
    $env:RELEASE_DESCRIPTION = "$env:APPVEYOR_REPO_COMMIT_MESSAGE`n$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"
deploy:
- provider: Environment
  name: GitHub Releases